kind: ConfigMap
apiVersion: v1
metadata:
  name: movie-service-config
  namespace: dev
data:
  DATABASE_URI: "postgresql://movie:password@postgres-movie-service:5432/movie_db"
  #DATABASE_URI: "postgresql://movie:password@postgres-movie-service:5432/movie_db_dev"
  CAST_SERVICE_HOST_URL: "http://cast-db-service:8000/api/v1/casts/"