apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-movie-configmap
  labels:
    app: postgres-movie-db
  namespace: dev
data:
  POSTGRES_USER: "movie"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "movie_db"
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cast-configmap
  labels:
    app: postgres-cast-db
  namespace: dev
data:
  POSTGRES_USER: "cast"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "cast_db"
