namespace: dev

configmap:
  postgres-cast:
    name: postgres-cast-configmap
    POSTGRES_USER: "cast"
    POSTGRES_PASSWORD: "password"
    POSTGRES_DB: "cast_db_dev"

  postgres-movie:
    name: postgres-movie-configmap
    POSTGRES_USER: "movie_db_username"
    POSTGRES_PASSWORD: "movie_db_password"
    POSTGRES_DB: "movie_db_dev"
  
  cast-service:
    name: cast-service-config
    uri: "postgresql://cast_db_username:cast_db_password@postgres-cast-service:5432/cast_db_dev"

  movie-service:
    name: movie-service-config
    uri: "postgresql://movie_db_username:movie_db_password@postgres-movie-service:5432/movie_db_dev"
    cast_service_uri: "http://cast-db-service:8000/api/v1/casts/"

  nginx:
    name: nginx-config

Deployment:
  imagePullPolicy: IfNotPresent
  replicaCount: 1

  nginx:
    name: nginx
    image: nginx
    port: 9090

  postgres:
    image: postgres:12.1-alpine
    mountPath: /var/lib/postgresql/data/
    ports: 5432
  
  movie-db:
    name: postgres-movie-db

  cast-db:
    name: postgres-movie-db

  cast-service:
    image: superbero/cast_service:latest
    name: cast-svc-deploy

  movie-service:
    image: superbero/movie_service:latest

volumes:
  storageClassName: standard
  accessModes: ReadWriteMany
  persistentvolume:
    name: postgres-data
    size: 5Gi
    volume_path: /Users/admin/data
   
  persistentvolumeclaim:
    size: 2Gi
    storageClassName: standard
    accessModes: ReadWriteMany

    cast-db:
      name: postgres-data-cast
    
    movie-db:
      name: postgres-data-movie

services:
  postgres-cast:
    name: postgres-cast-service
    type: ClusterIP
    port: 5432
    targetPort: 5432
  
  postgres-movie:
    name: postgres-movie-service
    type: ClusterIP
    ports:  5432
    targetPort: 5432

  nginx:
    type: LoadBalancer
    ports: 9090
    name: nginx-service

  movie-service:
    name: movie-db-service

  cast-service:
    name: cast-db-service
