apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-movie-configmap
  labels:
    app: movie_db
  namespace: dev
data:
  POSTGRES_USER: "movie_db_username"
  POSTGRES_PASSWORD: "movie_db_password"
  POSTGRES_DB: "movie_db_dev"
 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cast-configmap
  labels:
    app: cast_db
data:
  POSTGRES_USER: "cast_db_username"
  POSTGRES_PASSWORD: "cast_db_password"
  POSTGRES_DB: "cast_db_dev"
