kind: Service
apiVersion: v1
metadata:
  name:  nginx-service
  namespace: dev
spec:
  selector:
    app:  nginx
  type:  LoadBalancer 
  ports:
  - name:  nginx-loadbalancer
    port:  9090
    protocol: TCP
    targetPort:  9090