kind: ConfigMap
apiVersion: v1
metadata:
  name: movie-service-config
  namespace: dev
data:
  DATABASE_URI: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"
  CAST_SERVICE_HOST_URL: "http://cast_service:8000/api/v1/casts/"