apiVersion: apps/v1
kind: Deployment
metadata:
  name:  movie-svc-deploy
  namespace: dev
  labels:
    app:  movie-svc-deploy
spec:
  selector:
    matchLabels:
      app: movie-svc-deploy
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  movie-svc-deploy
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  movie-svc-deploy
        image:  superbero/movie_service:latest
        command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        envFrom:
          - configMapRef:
              name: movie-service-config
       