kind: Service
apiVersion: v1
metadata:
  name:  movie-service
  namespace: dev
spec:
  selector:
    app:  movie-svc-deploy
  type:  ClusterIP
  ports:
  - name:  tcp
    port:  8000
    targetPort:  8000